version: '3.8'
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    volumes:
      - ./bot:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app
