services:
  frontend:
    build:
      context: ./frontend
      secrets:
        - frontend_env
    env_file:
      - ./frontend/.env 
    ports:
      - "3004:3000"

  backend:
    build:
      context: ./bot
      secrets:
        - backend_env
    env_file:
      - ./bot/.env
    ports:
      - "3001:3001"

secrets:
  frontend_env:
    file: ./frontend/.env
  backend_env:
    file: ./bot/.env
