services:
  blimp:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Build-time args for Next.js
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_DISCORD_BOT_INVITE_URL=${NEXT_PUBLIC_DISCORD_BOT_INVITE_URL}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        - DATABASE_URL=${DATABASE_URL}
        - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
        - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
        - API_PORT=${API_PORT}
        - WS_PORT=${WS_PORT}
        - REDIS_URL=${REDIS_URL}
    ports:
      - "3004:3000"  # Frontend
      - "3001:3001"  # Bot API
      - "3002:3002"  # WebSocket
    environment:
      # Runtime environment variables
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_DISCORD_BOT_INVITE_URL: ${NEXT_PUBLIC_DISCORD_BOT_INVITE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      TOKEN: ${TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      WS_PORT: ${WS_PORT}
      API_PORT: ${API_PORT}
      GUILD_ID: ${GUILD_ID}
      OWNER_ID: ${OWNER_ID}
      NODE_ENV: production
    restart: unless-stopped